# Copyright (c) The OGX Contributors.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

"""
Unit tests for pgvector metadata filter translation (database-free).

These tests pin the SQL generated by PGVectorIndex._translate_comparison_filter
for in/nin filters: homogeneous bool/numeric lists get the same typed casts as
scalar comparisons, while other lists keep the text comparison.
"""

from unittest.mock import AsyncMock, MagicMock

import pytest

from ogx.providers.remote.vector_io.pgvector.config import PGVectorHNSWVectorIndex
from ogx.providers.remote.vector_io.pgvector.pgvector import PGVectorIndex
from ogx_api import VectorStore
from ogx_api.filters import ComparisonFilter, CompoundFilter


@pytest.fixture
def pgvector_index() -> PGVectorIndex:
    store = MagicMock(spec=VectorStore)
    store.identifier = "test-store-123"
    store.embedding_dimension = 128

    pool = MagicMock()
    pool_factory = AsyncMock(return_value=pool)

    return PGVectorIndex(
        vector_store=store,
        dimension=128,
        pool_factory=pool_factory,
        distance_metric="COSINE",
        vector_index=PGVectorHNSWVectorIndex(),
    )


def _expr(key: str) -> str:
    return f"document->'metadata'->>'{key}'"


def test_in_boolean_list_uses_boolean_cast(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="published", value=[True]), param_idx=1
    )

    assert clause == f"({_expr('published')})::boolean IN ($1)"
    assert params == [True]
    assert next_idx == 2


def test_nin_boolean_list_uses_boolean_cast(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="nin", key="published", value=[True]), param_idx=1
    )

    assert clause == f"({_expr('published')})::boolean NOT IN ($1)"
    assert params == [True]
    assert next_idx == 2


def test_in_multiple_booleans_uses_boolean_cast(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="published", value=[True, False]), param_idx=1
    )

    assert clause == f"({_expr('published')})::boolean IN ($1, $2)"
    assert params == [True, False]
    assert next_idx == 3


def test_in_integer_list_uses_numeric_cast(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="year", value=[2023]), param_idx=1
    )

    assert clause == f"({_expr('year')})::numeric IN ($1)"
    assert params == [2023]
    assert next_idx == 2


def test_nin_mixed_int_float_list_uses_numeric_cast(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="nin", key="year", value=[2023.5, 1]), param_idx=1
    )

    assert clause == f"({_expr('year')})::numeric NOT IN ($1, $2)"
    assert params == [2023.5, 1]
    assert next_idx == 3


def test_in_bool_list_not_treated_as_numeric(pgvector_index) -> None:
    # bool is a subclass of int; the boolean branch must win
    clause, _, _ = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="published", value=[True]), param_idx=1
    )

    assert "::numeric" not in clause
    assert "::boolean" in clause


def test_in_string_list_keeps_text_comparison(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="topic", value=["ai", "programming"]), param_idx=1
    )

    assert clause == f"{_expr('topic')} IN ($1, $2)"
    assert params == ["ai", "programming"]
    assert next_idx == 3


def test_in_mixed_type_list_keeps_text_comparison(pgvector_index) -> None:
    clause, params, _ = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="year", value=[2023, "2024"]), param_idx=1
    )

    assert clause == f"{_expr('year')} IN ($1, $2)"
    assert params == ["2023", "2024"]


def test_nin_mixed_bool_int_list_keeps_text_comparison(pgvector_index) -> None:
    clause, params, _ = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="nin", key="published", value=[True, 1]), param_idx=1
    )

    assert clause == f"{_expr('published')} NOT IN ($1, $2)"
    assert params == ["True", "1"]


def test_in_filter_respects_param_idx(pgvector_index) -> None:
    clause, _, next_idx = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="year", value=[2023, 2024]), param_idx=2
    )

    assert clause == f"({_expr('year')})::numeric IN ($2, $3)"
    assert next_idx == 4


def test_in_rejects_non_list_value(pgvector_index) -> None:
    with pytest.raises(ValueError, match="'in' filter requires a list value"):
        pgvector_index._translate_comparison_filter(
            ComparisonFilter(type="in", key="published", value=True), param_idx=1
        )


def test_nin_rejects_non_list_value(pgvector_index) -> None:
    with pytest.raises(ValueError, match="'nin' filter requires a list value"):
        pgvector_index._translate_comparison_filter(
            ComparisonFilter(type="nin", key="published", value=True), param_idx=1
        )


def test_in_cast_consistent_with_scalar_bool_comparison(pgvector_index) -> None:
    scalar_clause, _, _ = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="eq", key="published", value=True), param_idx=1
    )
    list_clause, _, _ = pgvector_index._translate_comparison_filter(
        ComparisonFilter(type="in", key="published", value=[True]), param_idx=1
    )

    assert scalar_clause == f"({_expr('published')})::boolean = $1"
    assert list_clause.startswith(f"({_expr('published')})::boolean IN ")


def test_compound_and_threads_params_for_in_filters(pgvector_index) -> None:
    clause, params, next_idx = pgvector_index._translate_compound_filter(
        CompoundFilter(
            type="and",
            filters=[
                ComparisonFilter(type="in", key="published", value=[True]),
                ComparisonFilter(type="nin", key="topic", value=["ai"]),
            ],
        ),
        param_idx=1,
    )

    assert clause == f"(({_expr('published')})::boolean IN ($1)) AND ({_expr('topic')} NOT IN ($2))"
    assert params == [True, "ai"]
    assert next_idx == 3


def test_unknown_comparison_operator_rejected(pgvector_index) -> None:
    unsupported = ComparisonFilter.model_construct(type="between", key="year", value=[2023])

    with pytest.raises(ValueError, match="Unknown comparison operator"):
        pgvector_index._translate_comparison_filter(unsupported, param_idx=1)
